version: '3'

services:
  php:
    container_name: php_container
    build:
      context: ./php
    depends_on:
      - mysql
    links:
      - mysql:mysql
    volumes:
      - "./public_html:/var/www/html:cached"
    restart: always

  mysql:
    container_name: mysql_container
    image: mysql:latest
    volumes:
      - "./mysql/.data:/var/lib/mysql"
      - "./mysql/config/my.cnf:/usr/local/etc/mysql/my.cnf"
    env_file: "./.env"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always

  nginx:
    container_name: nginx_container
    image: nginx:latest
    volumes:
      - "./public_html/:/var/www/html"
      - "./nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/logs:/var/log/nginx"
    depends_on:
      - php
    links:
      - php
    restart: always

  phpmyadmin:
    container_name: pma_container
    image: phpmyadmin/phpmyadmin
    depends_on:
     - mysql
    links:
        - mysql
    environment:
        PMA_HOST: mysql
    restart: always
